using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EMP.Web.Services.Reports
{
    public class ReportContext
    {
        public string CompanyName { get; set; } = "Your Company";
        public byte[]? Logo { get; set; }
        public string Title { get; set; } = "Report";
        public DateTime? From { get; set; }
        public DateTime? To { get; set; }
        public string CreatedBy { get; set; } = "—";
    }

    /// <summary>Renders a tabular PDF with a consistent branded header (logo, company,
    /// title, reporting period and the name of who generated it) and a paged footer.</summary>
    public static class PdfReportBuilder
    {
        public static byte[] BuildTable(ReportContext ctx, string[] headers, IEnumerable<string[]> rows)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);

                    page.Header().Element(h => BuildHeader(h, ctx));

                    page.Content().PaddingTop(12).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn(28); // row number
                            for (int i = 1; i < headers.Length; i++)
                            {
                                columns.RelativeColumn();
                            }
                        });

                        table.Header(header =>
                        {
                            foreach (var h in headers)
                            {
                                header.Cell().Element(HeaderCell).Text(h);
                            }
                        });

                        foreach (var r in rows)
                        {
                            foreach (var value in r)
                            {
                                table.Cell().Element(DataCell).Text(value ?? string.Empty);
                            }
                        }

                        static IContainer HeaderCell(IContainer c) => c
                            .PaddingVertical(5).PaddingHorizontal(3)
                            .BorderBottom(1).BorderColor(Colors.Grey.Medium)
                            .DefaultTextStyle(x => x.SemiBold());

                        static IContainer DataCell(IContainer c) => c
                            .PaddingVertical(4).PaddingHorizontal(3)
                            .BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2);
                    });

                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("Page ");
                        text.CurrentPageNumber();
                        text.Span(" of ");
                        text.TotalPages();
                    });
                });
            });

            return document.GeneratePdf();
        }

        private static void BuildHeader(IContainer container, ReportContext ctx)
        {
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    if (ctx.Logo is { Length: > 0 })
                    {
                        row.ConstantItem(90).MaxHeight(48).AlignLeft().AlignMiddle().Image(ctx.Logo).FitArea();
                        row.ConstantItem(12);
                    }

                    row.RelativeItem().Column(info =>
                    {
                        info.Item().Text(ctx.CompanyName).FontSize(16).Bold();
                        info.Item().Text(ctx.Title).FontSize(13).SemiBold().FontColor(Colors.Grey.Darken2);
                    });
                });

                var period = (ctx.From.HasValue || ctx.To.HasValue)
                    ? $"Period: {(ctx.From.HasValue ? ctx.From.Value.ToString("yyyy-MM-dd") : "…")} to {(ctx.To.HasValue ? ctx.To.Value.ToString("yyyy-MM-dd") : "…")}"
                    : "Period: All";

                col.Item().PaddingTop(6).Text($"{period}    |    Generated by {ctx.CreatedBy} on {DateTime.Now:yyyy-MM-dd HH:mm}")
                    .FontSize(9).FontColor(Colors.Grey.Darken1);

                col.Item().PaddingTop(6).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
            });
        }
    }
}
